//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEventStore.Persistence.GetEventStore {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NEventStore.Persistence.GetEventStore.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to use storage after it has been disposed..
        /// </summary>
        internal static string AlreadyDisposed {
            get {
                return ResourceManager.GetString("AlreadyDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to commit {0} events on stream &apos;{1}&apos; at sequence {2} in bucket &apos;{3}&apos;..
        /// </summary>
        internal static string AttemptingToCommit {
            get {
                return ResourceManager.GetString("AttemptingToCommit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit &apos;{0}&apos; persisted successfully..
        /// </summary>
        internal static string CommitPersisted {
            get {
                return ResourceManager.GetString("CommitPersisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concurrent write detected..
        /// </summary>
        internal static string ConcurrentWriteDetected {
            get {
                return ResourceManager.GetString("ConcurrentWriteDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting stream &apos;{0}&apos; from bucket &apos;{1}&apos;..
        /// </summary>
        internal static string DeletingStream {
            get {
                return ResourceManager.GetString("DeletingStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deserializing commit from record using serializer of type &apos;{0}&apos;..
        /// </summary>
        internal static string DeserializingCommit {
            get {
                return ResourceManager.GetString("DeserializingCommit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate commit detected; throwing..
        /// </summary>
        internal static string DuplicateCommit {
            get {
                return ResourceManager.GetString("DuplicateCommit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting all commits for stream &apos;{0}&apos; between revisions &apos;{1}&apos; and &apos;{2}&apos;..
        /// </summary>
        internal static string GettingAllCommitsBetween {
            get {
                return ResourceManager.GetString("GettingAllCommitsBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting all commits from &apos;{0}&apos; forward from bucket &apos;{0}&apos;..
        /// </summary>
        internal static string GettingAllCommitsFrom {
            get {
                return ResourceManager.GetString("GettingAllCommitsFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting all commits from checkpoint &apos;{0}&apos;..
        /// </summary>
        internal static string GettingAllCommitsFromCheckpoint {
            get {
                return ResourceManager.GetString("GettingAllCommitsFromCheckpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting all commits from &apos;{0}&apos; to &apos;{1}&apos;..
        /// </summary>
        internal static string GettingAllCommitsFromTo {
            get {
                return ResourceManager.GetString("GettingAllCommitsFromTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing storage engine..
        /// </summary>
        internal static string InitializingStorage {
            get {
                return ResourceManager.GetString("InitializingStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object has been disposed and cannot be used..
        /// </summary>
        internal static string ObjectAlreadyDisposed {
            get {
                return ResourceManager.GetString("ObjectAlreadyDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open connection &apos;{0}&apos;..
        /// </summary>
        internal static string OpenFailed {
            get {
                return ResourceManager.GetString("OpenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening connection &apos;{0}&apos;..
        /// </summary>
        internal static string OpeningConnection {
            get {
                return ResourceManager.GetString("OpeningConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening master connection &apos;{0}&apos;.
        /// </summary>
        internal static string OpeningMasterConnection {
            get {
                return ResourceManager.GetString("OpeningMasterConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening new threaded scope for key &apos;{0}&apos;; scope is root: {1}..
        /// </summary>
        internal static string OpeningThreadScope {
            get {
                return ResourceManager.GetString("OpeningThreadScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purging all stored data for bucket &apos;{0}&apos;..
        /// </summary>
        internal static string PurgingBucket {
            get {
                return ResourceManager.GetString("PurgingBucket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purging all stored data..
        /// </summary>
        internal static string PurgingStorage {
            get {
                return ResourceManager.GetString("PurgingStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutting down persistence..
        /// </summary>
        internal static string ShuttingDownPersistence {
            get {
                return ResourceManager.GetString("ShuttingDownPersistence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage threw exception of type &apos;{0}&apos;, wrapping and re-throwing..
        /// </summary>
        internal static string StorageThrewException {
            get {
                return ResourceManager.GetString("StorageThrewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to streamId is null, empty, or whitespace..
        /// </summary>
        internal static string StreamIdIsNullEmptyOrWhiteSpace {
            get {
                return ResourceManager.GetString("StreamIdIsNullEmptyOrWhiteSpace", resourceCulture);
            }
        }
    }
}
